### PR TITLE
feat: features

### PR DESCRIPTION
**Pull request by yqrashawn**
CU-4znj3e
CU-51nmnk
CU-51u63g
CU-51u645
CU-4vu27z
CU-f8xv6z
CU-4znd1m
CU-4vukr9
CU-4xx8qt

### CODE REVIEW

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-51u63g display gasprice in drip](https://app.clickup.com/t/51u63g)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-4znj3e portal 0.5.3发送cfx时显示Oceanus网络](https://app.clickup.com/t/4znj3e)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-f8xv6z willUserPayTxFee undefined error](https://app.clickup.com/t/f8xv6z)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-51u645 show gas price too low when gas price is below 1drip](https://app.clickup.com/t/51u645)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-51nmnk 签名页面，点高级，报错了](https://app.clickup.com/t/51nmnk)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-4xx8qt remove 1029 timestamp in next portal release](https://app.clickup.com/t/4xx8qt)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-4znd1m tx confirm page still showing oceanus](https://app.clickup.com/t/4znd1m)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-4vukr9 发送CFX的高级选项里，gas limit输入问题](https://app.clickup.com/t/4vukr9)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-4vu27z 普通转账的时候, 因为 gas fee 过少 显示为0](https://app.clickup.com/t/4vu27z)

**Comment by yqrashawn** [comment]
releated issue
#278

**Comment by yqrashawn** [comment]
CU-cwphn5
CU-4tufq8

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-4nwr18 余额显示问题，当0.xxxx，默认不显示0，很多人不理解，看是否有必要加上0的展示](https://app.clickup.com/t/4nwr18)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-4zxqmy signed message with wrong address 签名时显示的账号不对（多个账号，对多个网站授权）](https://app.clickup.com/t/4zxqmy)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-4vvgf1 gasprice shouldn't be able to set to 0](https://app.clickup.com/t/4vvgf1)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-4tufq8 更新 portal 用到的 scan 的 api](https://app.clickup.com/t/4tufq8)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-cwphn5 portal 添加代币时，没有 token 图标](https://app.clickup.com/t/cwphn5)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-4nt6ye 更新后出现旧的登录页面](https://app.clickup.com/t/4nt6ye)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-4xw5at portal won't recheck against sponsor info if there's insufficient balance error](https://app.clickup.com/t/4xw5at)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-51q7he reestimate on balance change when user is send to contract address](https://app.clickup.com/t/51q7he)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-53r4de 导出私钥页面输入错误的密码，密码提示信息与选择语言不一致](https://app.clickup.com/t/53r4de)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-4vryvk tx confirmation notification on testnet leads to mainnet scan](https://app.clickup.com/t/4vryvk)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-4vqxec 小窗口下 portal 授权页面 ui 重叠](https://app.clickup.com/t/4vqxec)

**Review by angelia-yuqi-personal — APPROVED** [review]

**Pull request merged**
